// File path: src/app/layout.js

import './globals.css';

export const metadata = {
  title: 'ITP App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}